version: "3.7"

services:
  busca-api:
    build:
      context: .
      target: busca-hoteis
    ports:
      - 3000:3000
    container_name: busca-api
    environment:
      - DATABASE_URL=postgres://hotels:hotels@db:5432/hotels
    depends_on:
      - db

  reserva-api:
    build:
      context: .
      target: reserva
    ports:
      - 3001:3001
    container_name: reserva-api
    environment:
      - DATABASE_URL=postgres://hotels:hotels@db:5432/hotels
    depends_on:
      - db

  cancelamento-api:
    build:
      context: .
      target: cancelamento
    ports:
      - 3002:3002
    container_name: cancelamento-api
    environment:
      - DATABASE_URL=postgres://hotels:hotels@db:5432/hotels
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine
    hostname: db
    container_name: db
    command: "postgres -c max_connections=1000 -c shared_buffers=200MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hotels
      - POSTGRES_DB=hotels
      - POSTGRES_PASSWORD=hotels
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "hotels"]
      timeout: 10s
      interval: 10s
      retries: 10

networks:
  default:
    driver: bridge
    name: av-n2-samuelfr
